### ISSUE TITLE
Kalipso unexpected identifier

### ISSUE THREAD

**Issue by Locituscom** [stratosphereips/StratosphereLinuxIPS#103]
When starting kalipso it throws this error despite all packages being installed.

`$ ./kalipso.sh
/opt/StratosphereLinuxIPS/node_modules/strip-ansi/index.js:1
import ansiRegex from 'ansi-regex';
       ^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/StratosphereLinuxIPS/modules/kalipso/kalipso_widgets/kalipso_tree.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)`

**Comment by eldraco** [comment]
Thanks. Let us check this. It was in master branch right? or develop? Did you follow the install instructions?
`sudo apt-get -y install curl git redis python3.7-minimal python3-redis python3-pip python3-watchdog nodejs npm`
`python3 -m pip install --upgrade pip`
`pip3 install maxminddb colorama validators urllib3 numpy sklearn pandas certifi keras redis==3.4.1 netaddr slackclient stix2 cabby ipwhois tzlocal`
`pip3 install --ignore-installed six`
`npm install blessed blessed-contrib redis async chalk strip-ansi@6.0.0 clipboardy fs sorted-array-async yargs`

**Comment by Locituscom** [comment]
Hi, yes I followed them as best as I could at least. Some of the install documentation seemed a bit spread out over blog posts and "real" documentation. Yes, I'm using the master branch.

After running you suggested commands, only "six" was a missing package (see full output below) but now yargs thinks my node version is too low (I'm using the ubuntu 20.04 default).

`mr@ids:/opt/StratosphereLinuxIPS$ sudo apt-get -y install curl git redis python3.7-minimal python3-redis python3-pip python3-watchdog nodejs npm
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3.7-minimal
E: Couldn't find any package by glob 'python3.7-minimal'
E: Couldn't find any package by regex 'python3.7-minimal'
mr@ids:/opt/StratosphereLinuxIPS$ python3 -m pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /usr/local/lib/python3.8/dist-packages (21.1.3)
mr@ids:/opt/StratosphereLinuxIPS$ pip3 install maxminddb colorama validators urllib3 numpy sklearn pandas certifi keras redis==3.4.1 netaddr slackclient stix2 cabby ipwhois tzlocal
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: maxminddb in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (0.4.3)
Requirement already satisfied: validators in /usr/local/lib/python3.8/dist-packages (0.18.2)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (1.25.8)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (1.19.5)
Requirement already satisfied: sklearn in /usr/local/lib/python3.8/dist-packages (0.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (1.3.0)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (2019.11.28)
Requirement already satisfied: keras in /usr/local/lib/python3.8/dist-packages (2.4.3)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (3.4.1)
Collecting netaddr
  Downloading netaddr-0.8.0-py2.py3-none-any.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 17.1 MB/s
Requirement already satisfied: slackclient in /usr/local/lib/python3.8/dist-packages (2.9.3)
Requirement already satisfied: stix2 in /usr/local/lib/python3.8/dist-packages (2.1.0)
Requirement already satisfied: cabby in /usr/local/lib/python3.8/dist-packages (0.1.23)
Requirement already satisfied: ipwhois in /usr/local/lib/python3.8/dist-packages (1.2.0)
Requirement already satisfied: tzlocal in /usr/lib/python3/dist-packages (2.1b1)
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.8/dist-packages (from validators) (1.15.0)
Requirement already satisfied: decorator>=3.4.0 in /usr/local/lib/python3.8/dist-packages (from validators) (5.0.9)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.8/dist-packages (from sklearn) (0.24.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.1)
Requirement already satisfied: h5py in /usr/local/lib/python3.8/dist-packages (from keras) (3.1.0)
Requirement already satisfied: scipy>=0.14 in /usr/local/lib/python3.8/dist-packages (from keras) (1.7.0)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from keras) (5.3.1)
Requirement already satisfied: aiohttp<4.0.0,>3.5.2 in /usr/local/lib/python3.8/dist-packages (from slackclient) (3.7.4.post0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp<4.0.0,>3.5.2->slackclient) (3.0.1)
Requirement already satisfied: chardet<5.0,>=2.0 in /usr/lib/python3/dist-packages (from aiohttp<4.0.0,>3.5.2->slackclient) (3.0.4)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.8/dist-packages (from aiohttp<4.0.0,>3.5.2->slackclient) (5.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp<4.0.0,>3.5.2->slackclient) (1.6.3)
Requirement already satisfied: attrs>=17.3.0 in /usr/lib/python3/dist-packages (from aiohttp<4.0.0,>3.5.2->slackclient) (19.3.0)
Requirement already satisfied: typing-extensions>=3.6.5 in /usr/local/lib/python3.8/dist-packages (from aiohttp<4.0.0,>3.5.2->slackclient) (3.7.4.3)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp<4.0.0,>3.5.2->slackclient) (2.8)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from stix2) (2.22.0)
Requirement already satisfied: simplejson in /usr/lib/python3/dist-packages (from stix2) (3.16.0)
Requirement already satisfied: stix2-patterns>=1.2.0 in /usr/local/lib/python3.8/dist-packages (from stix2) (1.3.2)
Requirement already satisfied: antlr4-python3-runtime~=4.8.0 in /usr/local/lib/python3.8/dist-packages (from stix2-patterns>=1.2.0->stix2) (4.8)
Requirement already satisfied: libtaxii>=1.1.111 in /usr/local/lib/python3.8/dist-packages (from cabby) (1.1.119)
Requirement already satisfied: colorlog in /usr/local/lib/python3.8/dist-packages (from cabby) (5.0.1)
Requirement already satisfied: furl>=0.4.7 in /usr/local/lib/python3.8/dist-packages (from cabby) (2.1.2)
Requirement already satisfied: orderedmultidict>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from furl>=0.4.7->cabby) (1.0.1)
Requirement already satisfied: lxml>=2.2.3 in /usr/local/lib/python3.8/dist-packages (from libtaxii>=1.1.111->cabby) (4.6.3)
Requirement already satisfied: dnspython<=2.0.0 in /usr/local/lib/python3.8/dist-packages (from ipwhois) (2.0.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn->sklearn) (2.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.8/dist-packages (from scikit-learn->sklearn) (1.0.1)
Installing collected packages: netaddr
  WARNING: The script netaddr is installed in '/home/mr/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed netaddr-0.8.0
mr@ids:/opt/StratosphereLinuxIPS$ pip3 install --ignore-installed six
Defaulting to user installation because normal site-packages is not writeable
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.5.0 requires six~=1.15.0, but you have six 1.16.0 which is incompatible.
Successfully installed six-1.16.0
mr@ids:/opt/StratosphereLinuxIPS$ npm install blessed blessed-contrib redis async chalk strip-ansi@6.0.0 clipboardy fs sorted-array-async yargs
npm WARN saveError ENOENT: no such file or directory, open '/opt/StratosphereLinuxIPS/package.json'
npm WARN notsup Unsupported engine for yargs@17.0.1: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: yargs@17.0.1
npm WARN enoent ENOENT: no such file or directory, open '/opt/StratosphereLinuxIPS/package.json'
npm WARN StratosphereLinuxIPS No description
npm WARN StratosphereLinuxIPS No repository field.
npm WARN StratosphereLinuxIPS No README data
npm WARN StratosphereLinuxIPS No license field.

+ clipboardy@2.3.0
+ chalk@4.1.1
+ redis@3.1.2
+ async@3.2.0
+ blessed-contrib@4.10.0
+ blessed@0.1.81
+ fs@0.0.1-security
+ yargs@17.0.1
+ strip-ansi@6.0.0
+ sorted-array-async@0.0.7
added 12 packages from 8 contributors, updated 10 packages, moved 1 package and audited 180 packages in 2.665s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

mr@ids:/opt/StratosphereLinuxIPS$ ./kalipso.sh
/opt/StratosphereLinuxIPS/node_modules/yargs/build/index.cjs:1
"use strict";var t=require("assert");class e extends Error{constructor(t){super(t||"yargs error"),this.name="YError",Error.captureStackTrace(this,e)}}let s,n=[];function i(t,o,a,h){s=h;let l={};if(Object.prototype.hasOwnProperty.call(t,"extends")){if("string"!=typeof t.extends)return l;const r=/\.json|\..*rc$/.test(t.extends);let h=null;if(r)h=function(t,e){return s.path.resolve(t,e)}(o,t.extends);else try{h=require.resolve(t.extends)}catch(e){return t}!function(t){if(n.indexOf(t)>-1)throw new e(`Circular extended configurations: '${t}'.`)}(h),n.push(h),l=r?JSON.parse(s.readFileSync(h,"utf8")):require(t.extends),delete t.extends,l=i(l,s.path.dirname(h),a,s)}return n=[],a?r(l,t):Object.assign({},l,t)}function r(t,e){const s={};function n(t){return t&&"object"==typeof t&&!Array.isArray(t)}Object.assign(s,t);for(const i of Object.keys(e))n(e[i])&&n(s[i])?s[i]=r(t[i],e[i]):s[i]=e[i];return s}function o(t){const e=t.replace(/\s{2,}/g," ").split(/\s+(

Error: yargs supports a minimum Node.js version of 12. Read our version support policy: https://github.com/yargs/yargs#supported-nodejs-versions
    at Object.<anonymous> (/opt/StratosphereLinuxIPS/node_modules/yargs/build/index.cjs:1:55294)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/StratosphereLinuxIPS/node_modules/yargs/index.cjs:5:30)
    at Module._compile (internal/modules/cjs/loader.js:778:30)`

**Comment by Locituscom** [comment]
Hi

I worked around the issue by installing node via npm and then modified the kalipso.sh script to run the newer node inside of node_modules.

**Comment by eldraco** [comment]
Thanks for the fix and trial. When you say another instance you mean an older one? If that is the case we will update Kalipso to use the new version and libraries.
Thanks!

**Comment by Locituscom** [comment]
When using apt-get to install node I get one version installed in /usr/bin/node and when I use npm to install node, I get a new independant binary installed in node_modules/node/bin/node which is of a newer version.

Here's the result of that and what I changed in kalipso.sh

mr@ids:/opt/StratosphereLinuxIPS$ node --version
v10.19.0
mr@ids:/opt/StratosphereLinuxIPS$ /opt/StratosphereLinuxIPS/node_modules/node/bin/node --version
v16.4.0

mr@ids:/opt/StratosphereLinuxIPS$ cat ./kalipso.sh
#!/bin/sh
node='/opt/StratosphereLinuxIPS/node_modules/node/bin/node'
cd modules/kalipso
$node kalipso -l 2000
