### ISSUE TITLE
tzlocal package is missing in docker tensorflow-image

### ISSUE THREAD

**Issue by jwackito** [stratosphereips/StratosphereLinuxIPS#106]
The command `./slips.py -c slips.conf -f dataset/test3.binetflow` fails
```
/StratosphereLinuxIPS# ./slips.py -c slips.conf -f dataset/test3.binetflow
Slips. Version 0.7.3
https://stratosphereips.org

Traceback (most recent call last):
  File "./slips.py", line 327, in <module>
    from profilerProcess import ProfilerProcess
  File "/StratosphereLinuxIPS/profilerProcess.py", line 32, in <module>
    from tzlocal import get_localzone
ModuleNotFoundError: No module named 'tzlocal'
```
Solved after pip install it manually from inside the container
`/StratosphereLinuxIPS# pip install tzlocal`
but not sure the changes are permanent or be gone after reinit the container...

**Comment by willie-lin** [comment]
You can modify the Dockerfile file
Add a line "RUN pip3 install tzlocal"

**Comment by eldraco** [comment]
thanks! we added it already
