### ISSUE TITLE
The directory `/StratosphereIPs` inside the docker slips_light should be called `/StratosphereIPS`

### ISSUE THREAD

**Issue by eldraco** [stratosphereips/StratosphereLinuxIPS#1095]
**Describe the bug**
The directory `/StratosphereIPs` inside the docker slips_light should be called `/StratosphereIPS`

This seems like a typo, but it can have repercussions for people using -v for volumes from the outside.

**Expected behavior**
To be `/StratosphereIPS`
Branch
Docker running slips_light
Develop 1.1.4

Environment (please complete the following information):

OS: macos m1
Version: m1
Python version Python 3.10.12
Are you running slips in docker or locally? yes in docker
Docker version (if running slips in docker) 4.36.0
Commit hash: ( git rev-parse --short HEAD ): not shown in the docker version

**Comment by AbhiramMasna** [comment]
Hello @eldraco  I was wondering if i can contribute to this issue. I want to know if someone else is already working on it , if not i would like to work on it.

**Comment by AlyaGomaa** [comment]
hey @AbhiramMasna i'm already working on it, sorry. 

but hey feel free to check the rest of our issues, there's definitely something you can help us with there! :))

thankss

**Comment by eldraco** [comment]
yes, you can do it. Thanks

**Comment by AlyaGomaa** [comment]
fixed and republished slips_light image to docker hub
