### ISSUE TITLE
Trying to download the file Cyber_Threat_Coalition_Domain_Blacklist.intel

### ISSUE THREAD

**Issue by adabiraihan** [stratosphereips/StratosphereLinuxIPS#113]
Hi, 

is it taking a long time on this process or am I stuck?

`[UpdateManager] We should update the remote file https://raw.githubusercontent.com/CriticalPathSecurity/Zeek-Intelligence-Feeds/master/Cyber_Threat_Coalition_Domain_Blacklist.intel`
`[UpdateManager] Trying to download the file Cyber_Threat_Coalition_Domain_Blacklist.intel`

**Comment by AlyaGomaa** [comment]
Hello @adabiraihan, yes there was a problem with this TI file specifically, it had headers only without IoCs.
We fixed that in develop branch( 9bd3684a98fea2444f38453ddfc1d65f210e5fa8 ) and we'll patch master later.
Thanks for your feedback.

**Comment by adabiraihan** [comment]
Thank you !
