### ISSUE TITLE
[ASK] Integrating with SIEM

### ISSUE THREAD

**Issue by adabiraihan** [stratosphereips/StratosphereLinuxIPS#114]
Hi Dev,

Just curious. 
Is it possible to integrate this StratosphereLinuxIPS with SIEM for better visualization?

Thanks.

**Comment by AlyaGomaa** [comment]
Hi @adabiraihan, You can import the `alerts.json`  file generated by slips into a SIEM like Splunk no problem. 

![image](https://user-images.githubusercontent.com/41242896/142626195-184b4b47-f5be-44a8-b3c9-9fde6032d134.png)

**Comment by adabiraihan** [comment]
Thanks !!
