### ISSUE TITLE
Machine Learning Algorithm

### ISSUE THREAD

**Issue by adabiraihan** [stratosphereips/StratosphereLinuxIPS#115]
Hi Dev,

Is it right that below is the ML Algorithm used for detecting anomalies in Slips?

1. SVM for labeling our own dataset with malicious/normal
2. RNN for detecting C&C
3. LSTM for detecting C&C Channels
4. Non-ML (Normal Algorithm) for detecting Port Scanning 
CMIIW 

Sorry if i always asking, I'm doing this for my bachelor degree research paper :)

Thanks!

**Comment by eldraco** [comment]
Hi adabiraihan
I'm not sure what you mean with "below is the algorithm for detecting anomalies". There are several ML detectors in Slips, but only one is an anomaly detector.
1- Anomaly Detector uses the OCSVM | One-Class Support Vector Machines
2- The RNN uses LSTM fro CC
3- The flowmldetector uses Logistic Regression in flows
4- The rest of Slips uses behavioral techniques. 
5- There is an ensambling module not finished yet.

Better?
thanks

**Comment by adabiraihan** [comment]
Thanks dev, thats the answer i need.


Thank you ! :)
