### ISSUE TITLE
Kalipso Error

### ISSUE THREAD

**Issue by Uppa-Katom** [stratosphereips/StratosphereLinuxIPS#119]
I get this error when pressing enter to expand a timewindow in the kalipso GUI. Do you have any ideas on how to fix this? 

Thank you in advance :
![kailpso_2](https://user-images.githubusercontent.com/97445219/148759333-d8837ce6-49a8-4ed5-8195-710616836fd1.png)
[zeek_files.zip](https://github.com/stratosphereips/StratosphereLinuxIPS/files/7838493/zeek_files.zip)
)

**Comment by AlyaGomaa** [comment]
Hi @Uppa-Katom, This is solved in the latest [develop](https://github.com/stratosphereips/StratosphereLinuxIPS/tree/develop) branch  (1541c829355380ede31b48becaf7b1ce9a987275)

Thanks for reporting
