### ISSUE TITLE
A question about the profilerqueue

### ISSUE THREAD

**Issue by Sraq-Zit** [stratosphereips/StratosphereLinuxIPS#123]
I noticed that you use a shared queue between the InputProcess and ProfilerProcess.
My question is why do you use this queue for communication instead of Redis ?

**Comment by eldraco** [comment]
Hi Srqa-Zit
We use both Redis queues and process queues. But for different reasons. The process queue are usually to speed up the transfer of large amounts of data between process (pcap->input->profiling) as fast as possible and the Redis queues are used more in the pub/sub style of passing messages and not having a time critical response time. 
However this was not compared, so not really a strong reason. Do you know more about this?

**Comment by Sraq-Zit** [comment]
Hello,
Thank you for your quick response.
I just came across that profiler queue, and I wondered why using that instead of Redis, it popped into my mind the transfer speed criteria, but I thought I would ask maybe there is something else, so I think your answer clears things up.
