### ISSUE TITLE
Verbosity and debugging from config file is always ignored

### ISSUE THREAD

**Issue by arkamar** [stratosphereips/StratosphereLinuxIPS#13]
https://github.com/stratosphereips/StratosphereLinuxIPS/blob/7f483982c4384c025bf9fb0c771985e169697b89/slips.py#L55-L77
`args.verbose` and `args.debug` are set to theirs default value and comparison against `None` will always fail. Therefore, the code above is skiped and values from config file will never be used.

This issue refers to `newslips` branch

**Comment by eldraco** [comment]
Nice catch! thanks.
Solved it in commit 5d39f55
It was left behind from a previous version. The idea was to be sure that we will always have some value there.
