### ISSUE TITLE
Some questions about StratosphereIPS

### ISSUE THREAD

**Issue by Uppa-Katom** [stratosphereips/StratosphereLinuxIPS#154]
Hello there!
Thank you for the quick response so far!
There are a few small questions I have about the usage of Slips. So I'll write them all here:

1. Is it possible to see the stratosphere letters in the .timewindow file when an alert has been generated for that profile? Currently I see those only when an alert hasn't been generated for the profile. I was wondering if it is possible to change that.

2. Is there a way to change the connection length or the number of packets needed for a "CnC Detected" alert to be generated? I thought there might be a setting like that, but I couldn't find one in the configuration file.

3. I tried to change the config file to exclude the "Connection without DNS resolution" alert, but it still generates that alert. what am I doing wrong?

4. Is there a way to append multiple connections/alerts to the .timewindow file? From the example you've sent me, it seems like there could be multiple connection logs in that file. however I only get the last connection/alert in that file. Is there a way to change that?

**Comment by eldraco** [comment]
Hi Uppa-Katom
1- Yes it is, generate the log folder using the configuration option and then check the files there
2- There is no easy way to do that, but you can change the code in the profilerProcess.py file, function compute_symbol(), see here:

  ```
# Thresholds learnt from Stratosphere ips first version
              # Timeout time, after 1hs
              tto = timedelta(seconds=3600)
              tt1 = float(1.05)
              tt2 = float(1.3)
              tt3 = float(5)
              td1 = float(0.1)
              td2 = float(10)
              ts1 = float(250)
              ts2 = float(1100)
```
3- I don't understand your question. There are no alerts in the .timewindow file. All the alerts are in the alerts.log alerts.json files

tell us how it went!

Also remember you can join our public Discord and talk with us here https://discord.gg/YW9RRDwu
