### ISSUE TITLE
Solve our processes eating 100% of the CPU when idle

### ISSUE THREAD

**Issue by eldraco** [stratosphereips/StratosphereLinuxIPS#16]
Our processes do not block on the queues yet, so when there is no data to receive they eat the CPU.
But we need them to processes the input data as fast as possible.

**Comment by arkamar** [comment]
I solved the busy waiting issue in https://github.com/arkamar/StratosphereLinuxIPS/tree/i16 branch. Main problem was that we used the busy waiting
```python
while True:
	self.queue.empty():
		pass
	else:
		data = self.queue.get()
		do_job(data)
```
where `self.queue.empty()` is non-blocking method, but we should use blocking methods `put` and `get`.
```python
while True:
	data = self.queue.get()
	do_job(data)
```

Should I do a pull request?

**Comment by arkamar** [comment]
Well, it is still far from perfect, but at least something.

**Comment by eldraco** [comment]
Merged! Thanks a lot. It was a good code. I tested it and it worked much better!
