### ISSUE TITLE
Suggest to loosen the dependency on redis

### ISSUE THREAD

**Issue by Agnes-U** [stratosphereips/StratosphereLinuxIPS#163]
Dear developers, 

Your project StratosphereLinuxIPS requires "redis==3.5.3" in its dependency. After analyzing the source code, we found that the following versions of redis can also be suitable without affecting your project, i.e., redis 3.5.2. Therefore, we suggest to loosen the dependency on redis from "redis==3.5.3" to "redis>=3.5.2,<=3.5.3" to avoid any possible conflict for importing more packages or for downstream projects that may use ddos_script. 

May I pull a request to further loosen the dependency on redis?

By the way, could you please tell us whether such dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

<br />

----

Details: 

Your project (commit id: 3d1672567bf70e547a6bb76e4415c06b29ac1956) directly uses 7 APIs from package redis.

```
redis.client.Redis.ping, redis.client.Redis.flushdb, redis.exceptions.ResponseError.__init__, redis.client.Redis.__init__, redis.exceptions.ConnectionError.__init__, redis.client.PubSub.__init__, redis.exceptions.DataError.__init__
```

Beginning fromwhich, 7 functions are then indirectly called, including 4 redis's internal APIs and 3 outsider APIs as follows:
```
[/stratosphereips/StratosphereLinuxIPS]
+--redis.client.Redis.ping
|      +--redis.client.Redis.execute_command
|      |      +--redis.client.Redis.parse_response
+--redis.client.Redis.flushdb
|      +--redis.client.Redis.execute_command
+--redis.exceptions.ResponseError.__init__
+--redis.client.Redis.__init__
|      +--redis.connection.ConnectionPool.__init__
|      |      +--threading.Lock
|      |      +--redis.connection.ConnectionPool.reset
|      |      |      +--threading.Lock
|      |      |      +--os.getpid
|      +--warnings.warn
|      +--redis.client.CaseInsensitiveDict.__init__
|      |      +--redis._compat.iteritems
+--redis.exceptions.ConnectionError.__init__
+--redis.client.PubSub.__init__
|      +--redis.client.PubSub.reset
+--redis.exceptions.DataError.__init__
```

Since all these functions have not been changed between any version for package "redis" from [3.5.2] and 3.5.3. Therefore, we believe it is safe to loosen the corresponding dependency.

**Comment by AlyaGomaa** [comment]
Hello @Agnes-U 

You're right, i tested Slips with redis 3.5.2 and it's working fine.

Fixed. Thank You!
