### ISSUE TITLE
unlisted dependencies, error in documentation

### ISSUE THREAD

**Issue by Nubicola** [stratosphereips/StratosphereLinuxIPS#164]
**Describe the bug**
There are at least 2 unlisted dependencies that I had to install:
- validators
- psutil

Further there are some errors in the documentation

**To Reproduce**
git clone the repo as per installation instruction: 
git clone https://github.com/stratosphereips/StratosphereLinuxIPS.git

sudo ./install.sh --> no error
run slips:
./slips.py -c config/slips.conf -r datasets/hide-and-seek-short.pcap
--> unmet dependencies, validators and psutil. Fixed with pip3 install. 

Additional errors:
In section https://stratospherelinuxips.readthedocs.io/en/develop/installation.html#running-slips-for-the-first-time, the command is wrong.
a) it should be -f, not -r (I think)
b) datasets/hide-and-seek-short.pcap does not exist

**My environment**
Today I installed a completely new Ubuntu environment.

**Comment by AlyaGomaa** [comment]
Hello @Nubicola 

I believe we have validators, psutil and flask in our [requirements.txt](https://github.com/stratosphereips/StratosphereLinuxIPS/blob/master/requirements.txt) which is used by our [install.sh](https://github.com/stratosphereips/StratosphereLinuxIPS/blob/master/install.sh), not sure why you got the  unmet dependencies error, maybe the versions slips reuires of them aren't compatible with your python version?

And yes you're right, i just updated the errors in [running-slips-for-the-first-time](https://stratospherelinuxips.readthedocs.io/en/develop/installation.html#running-slips-for-the-first-time) docs, thank you for reporting.

**Comment by Nubicola** [comment]
Hi @AlyaGomaa 
OK, I see that the requirements.txt has all three in there. I didn't see any error when I ran install.sh. Maybe I missed it?

I'll close-with-comment since I don't have any further evidence and your part appears to be done correctly :)
