### ISSUE TITLE
Threshold calculation

### ISSUE THREAD

**Issue by sachinvernekar** [stratosphereips/StratosphereLinuxIPS#2]
Hi

From the blog, https://stratosphereips.org/stratosphere-ips-generation-of-the-behavioral-models.html
I see that special training methods were employed to determine the feature thresholds(size, duration, periodicity). Any reference to those methods shall be very helpful.

Thanks
Sachin

**Comment by sachinvernekar** [comment]
Hi
I got the required answer from your publication. https://www.researchgate.net/publication/271204142_Identifying_Modeling_and_Detecting_Botnet_Behaviors_in_the_Network

Thanks
Sachin

**Comment by eldraco** [comment]
Hi! Sorry for my late response. Glad you find it!
Was it useful?
