### ISSUE TITLE
Implement redis Publish–subscribe pattern to run specific code

### ISSUE THREAD

**Issue by eldraco** [stratosphereips/StratosphereLinuxIPS#20]
Implement in the main code and database.py file a pubsub mechanism (https://redis.io/topics/pubsub)
This will allow part of slips and the modules to ask for specific events to happen in the DB to act. Instead of searching the DB for some data, you can ask the DB to wake you up when the data arrives or changes.

For example, if your module wants to check the country of the src IPS you can ask the DB to call you back for each new src IP received (even maybe each new unique src IP received). This would decrease the work of the modules.

**Comment by arkamar** [comment]
Here, it should be pointed out that `PubSub.get_message()` is non-blocking by default in `redis-py` library, but their solution with `time.sleep(0.001)` is not elegant. However, we can use
```python
get_message(timeout=None)
```
if you don't mind to use undocumented feature of the library, to make it blocking.

**Comment by eldraco** [comment]
I agree with the idea and thanks for taking a look. I had no idea that was a problem!

**Comment by eldraco** [comment]
Implemented!
