### ISSUE TITLE
use OpenC2 language for p2p

### ISSUE THREAD

**Issue by AlyaGomaa** [stratosphereips/StratosphereLinuxIPS#201]
Created by Alya Gomaa via monday.com integration. 🎉

**Comment by HAPPYCODER505** [comment]
I want to work on it. Can you explain the problem to me?

**Comment by eldraco** [comment]
Hi! Yes, the idea of this task is to adapt part of our detections into using the OpenC2 language to report p2p alerts. The main issue is that now the alerts shared in the p2p system are not following any format.

If you want to work on this for the GSoC 2023 tell us in Discord and we can talk!

**Comment by eldraco** [comment]
I checked this task and I decided that we are not gonna be doing it now @HAPPYCODER505 

We are going to cancel this task for now since slips's p2p system is designed to take decisions independently and not in a centralised way with other components.
  

> The goal of the OpenC2 Language Specification is to provide a language for interoperating between functional elements of cyber defense systems. OpenC2 is a standardized language for the command and control of technologies that provide or support cyber defenses. By providing a common language for machine-to-machine communication, OpenC2 is vendor and application agnostic, enabling interoperability across a range of cyber security tools and applications. 
> The OpenC2 Language Specification defines the set of components to assemble a complete command and control Message and provides a framework so that the language can be extended
