### ISSUE TITLE
Do a good documentation of the stratoletters

### ISSUE THREAD

**Issue by AlyaGomaa** [stratosphereips/StratosphereLinuxIPS#205]
Created by Alya Gomaa via monday.com integration. 🎉

**Comment by Aman123lug** [comment]
@AlyaGomaa which file?

**Comment by Aman123lug** [comment]
Need to create new one ? @AlyaGomaa

**Comment by Aman123lug** [comment]
@AlyaGomaa what is stratoletters. where the file exits not able to find

**Comment by AlyaGomaa** [comment]
hello @Aman123lug Sorry for the late reply
In slips, There's a module called rnn-cc-detection, the strato letters are a way for that module to detect Command and control channels. they detect the periodicity and the duration of the flows and represent them in letters

they are displayed when you go to the web interface (start slips using -w) -> go to the "Outgoing" tab -> check the "Behavior" column
![image](https://user-images.githubusercontent.com/41242896/222411406-9b359570-9762-4a2b-9a9e-657371d69ce7.png)

You can read more about them here
https://www.researchgate.net/publication/303565124_Robots_against_robots_How_a_Machine_Learning_IDS_detected_a_novel_Linux_Botnet
and you can check the code if you want to document them for better understanding of how they work

let me see if they're explained in more detail somewhere

**Comment by AlyaGomaa** [comment]
apparently they are not properly documented anywhere and this is what this issue is all about
you can read the code, understand how they're generated, and document them maybe using graphs and examples etc.
let me know if you need help

**Comment by Aman123lug** [comment]
@AlyaGomaa Okay need to create readme.md file in the docs

**Comment by Aman123lug** [comment]
@AlyaGomaa In root:/StratoshpereIPS i run in base ./webinterface.sh. It's showing me Running on : http://127.0.01:55000 but it's not running

**Comment by Aman123lug** [comment]
> apparently they are not properly documented anywhere and this is what this issue is all about you can read the code, understand how they're generated, and document them maybe using graphs and examples etc. let me know if you need help

can you me please share me some resource where this is explain in a nice way. thank you
