### ISSUE TITLE
Realize that slips was not given a file to read or any file in the stdin, so stop slips.

### ISSUE THREAD

**Issue by eldraco** [stratosphereips/StratosphereLinuxIPS#22]
If we are not given a file with -r, or a stdin file, we should stop the execution.

**Comment by arkamar** [comment]
This one is quite simple, we just have to check a return value of this function
```python
os.isatty(file.fileno())
```
where `file` could represent `sys.stdin` or any other file opened by `open` function and exit if it returns `True`.

**Comment by eldraco** [comment]
Actually your code for doing the get already took care of this. So the input process is ending correctly all the time. Now I need to spread the 'news' in the other processes. Thanks!
