### ISSUE TITLE
Slips is not stopping while using the new statusbar

### ISSUE THREAD

**Issue by eldraco** [stratosphereips/StratosphereLinuxIPS#225]
**Describe the bug**
Slips does not stop alone when using the new status bar.
I waited more than 20 minutes. It is not about loading the TI

**To Reproduce**
./slips.py -f dataset/test3-mixed.binetflow

**Expected behavior**
To end

**Screenshots**

**Branch**
File: dataset/test3-mixed.binetflow
Branch: develop
Commit: 7571f6801b323cc96cb3ebda06e6653adb49401a
Slips start date: 2023/02/21 09:51:14.129269
Slips end date: 2023/02/21 10:59:05.259546

**Environment (please complete the following information):**
 - OS: linux
 - Version 5.18.0-2-amd64
 - Python version Python 3.9.2
 - Are you running slips in docker or locally? local

**Comment by HAPPYCODER505** [comment]
I want to work on it. Can you explain the problem to me?

**Comment by HAPPYCODER505** [comment]
Do I need to run slips on local system??

**Comment by pratikpradhan2606** [comment]
I would like to work this Issue. Can you assign it to me?

**Comment by HAPPYCODER505** [comment]
Ok sir .I will try my best.
