### ISSUE TITLE
Search failing in web interface - SLIPS v1.0.1

### ISSUE THREAD

**Issue by KdocTeach** [stratosphereips/StratosphereLinuxIPS#227]
**Describe the bug**
When doing a search in the TIMELINE tab of the web interface I get the following error:

DataTables warning: table id=table_timeline - Ajax error. For more information about this error, please see http://datatables.net/tn/7

This happens no matter what search term I enter.

**To Reproduce**
Using version 1.0.1 of slips running in docker container
Open web interface
Select any IP and time window
Enter any search term "Custom Search" box on TIMELINE tab.

**Expected behavior**
For example, when searching for Port 443: If I enter 443 in the Custom Search box, I expect to see a list of connections featuring only port 443 (This used to work in earlier versions of SLIPS

**Screenshots**
<img width="2036" alt="Screenshot 2023-02-23 at 4 30 36 PM" src="https://user-images.githubusercontent.com/92340701/221036386-00471869-fca0-48e0-b156-d098fd2608cc.png">

**Branch**
Master

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 docker image (running on Rocky 9 host)
 - Version 1.0.1
 - Python version 3.8.10
 - Are you running slips in docker or locally? Docker
 - Docker version (if running slips in docker) 23.0.1
 - Slips docker image used (if running slips in docker) slips:latest

**Comment by HAPPYCODER505** [comment]
I want to work on this issue.

**Comment by AlyaGomaa** [comment]
Hello @KdocTeach Thank you so much for reporting! 

@kamilababayeva  is currently working on it and will update this issue when it's fixed. 

Let us know if you find any more bugs! Thankss

**Comment by AlyaGomaa** [comment]
Hello @HAPPYCODER505 
You're welcomed to contribute to Slips any time!
Here's the contributor guide: https://stratospherelinuxips.readthedocs.io/en/develop/contributing.html
You can create a PR and we'll merge it. 
Thank youu

**Comment by eldraco** [comment]
Hi! yes, please try the develop branch to see if it was fixed.

**Comment by KdocTeach** [comment]
I just tested on the develop branch. The search works perfectly in the this branch.

Thank you all for you assistance. SLIPS is becoming an outstanding project!

**Comment by eldraco** [comment]
so happy you like it! @kamilababayeva fixed the web and is finishing some more tasks now
