### ISSUE TITLE
wrong_root in install.sh

### ISSUE THREAD

**Issue by Nitesh639** [stratosphereips/StratosphereLinuxIPS#233]
**Describe the bug**
A wrong path on install.sh

**To Reproduce**
1. Not provided a correct path of kalipso

**Expected behavior**
Should be ./modules/kalipso

**Screenshots**

![Screenshot from 2023-03-05 19-30-28](https://user-images.githubusercontent.com/66905080/222965037-24a2f009-66dd-4740-932f-40f3824be697.png)

**Branch**
Every branch

**Environment (please complete the following information):**
 - OS:  Linux
 - Python version [e.g. 3.8]

**Comment by AlyaGomaa** [comment]
PR merged. Thank you for your contribution!
