### ISSUE TITLE
Implement whitelists

### ISSUE THREAD

**Issue by eldraco** [stratosphereips/StratosphereLinuxIPS#24]
Implement a whitelist of IPs that should be completely ignored.

This should go in the main slips core files, not a module. And the ignoration of the flow should be as fast as possible in the processing of flows (probably the first thing done in the profiler)

We can have options for SRC IP whitelist, DST IP whitelist, or BOTH.
If it is BOTH:
- Ignore any flow/packet coming from or to this IP

If it is SRC IP:
- If a flow arrives coming from this SRC IP, ignore the flow.
- If a flow arrives coming for this DST IP, consider the flow

If it is DST IP:
- If a flow arrives coming from this SRC IP, consider the flow
- If a flow arrives coming for this DST IP, ignore the flow.

**Comment by AlyaGomaa** [comment]
Done
