### ISSUE TITLE
Regarding TensorFlow version

### ISSUE THREAD

**Issue by Nitesh639** [stratosphereips/StratosphereLinuxIPS#243]
**Describe the bug**
TensorFlow version in requirements.txt

**To Reproduce**
by changing the version of TensorFlow 

**Expected behavior**
It should be TensorFlow 2.11.0

**Screenshots**
![Screenshot from 2023-03-08 02-44-06](https://user-images.githubusercontent.com/66905080/224085872-21cc2d59-d9de-4485-9dc4-73f1af36c5eb.png)

**Branch**
Develop

**Environment (please complete the following information):**
 - OS:  Linux
 - Python version [e.g. 3.8]

**Comment by AlyaGomaa** [comment]
hey @Nitesh639 after changing the tensorflow version
how did you test your branch? did all slips tests pass inside your docker image?

**Comment by eldraco** [comment]
This is fixed already in new version.
