### ISSUE TITLE
Add an alert when there's a new HTTP flow

### ISSUE THREAD

**Issue by AlyaGomaa** [stratosphereips/StratosphereLinuxIPS#246]
This is a beginner-friendly feature request

## Goal
Set an evidence in slips when a new HTTP flow is found stating that the traffic is unencrypted

## How to implement it
this can be done by adding 1 function with the logic in the module that deals with HTTP traffic, here are the steps:
1. Check slips documentation to find the module that deals with HTTP traffic
2. write a function in that module, that sets a new evidence with the following details:
```
def set_evidence_http_traffic(self, timestamp, daddr, profileid, twid, uid):
   confidence = 1
   threat_level = 'low'
   source_target_tag = 'SendingUnencryptedData'
   category = 'Anomaly.Traffic'
   evidence_type = 'HTTPtraffic'
   attacker_direction = 'srcip' 
   attacker = profileid.split('_')[1]
   description = f'Unencrypted HTTP traffic from {attacker} to {daddr}.'
```
the above details should be enough for you to set evidence in slips

3. you can search in slips code what function to call in order to set evidence and how to use the above details (HINT: the function that sets evidence is in the database)
4. Find the directory inside ```dataset/``` that has some HTTP traffic (HINT: it's a zeek dir, not a pcap)
5. now after adding the function. test your code by running ```./slips.py -f <zeek_dir_from_step_4> -o output_dir``` and making sure there's no issues 

## Expected output
To test that your code is working, you should see the following line in ```output_dir/alerts.log```, maybe with different source and destination IPs

 
![image](https://user-images.githubusercontent.com/41242896/224546350-4c400759-feac-45fb-9d23-ad437f362f61.png)

If you're code is working and you can see the above line in your alerts.log, congrats! you can open a PR and we will merge it.

**Comment by pwnb0y** [comment]
hey @AlyaGomaa  I would love to work on it can you assign it to me

**Comment by AlyaGomaa** [comment]
hey @pwnb0y you can work on it and create a PR, no need to assign it to you.

**Comment by Aman123lug** [comment]
@AlyaGomaa Oh! got the idea ✌️ thanks for explaining

**Comment by pwnb0y** [comment]
hey @AlyaGomaa can you tell me how to extract http keyword from request or pcap file is that done by  profileid or anything else?

**Comment by AlyaGomaa** [comment]
hey @pwnb0y you should re-read the above steps again, you're not going to be using any PCAPs. just a zeek dir from our dataset/ dir

**Comment by AlyaGomaa** [comment]
Done by @haleelsada @ PR #258
