### ISSUE TITLE
Detect http executable mime type

### ISSUE THREAD

**Issue by AlyaGomaa** [stratosphereips/StratosphereLinuxIPS#254]
Created by Sebastian Garcia via monday.com integration. 🎉

**Comment by EmperialX** [comment]
Hello @mike-hunhoff , I came across this good first issue  and I would like to work on fixing it and would appreciate your guidance as I work on this issue. Let me know if you have any suggestions. can you assign me on this.

**Comment by AlyaGomaa** [comment]
hello @EmperialX you can open a PR with this feature, and let me know if you need help.
