### ISSUE TITLE
keep a history of the user agents used by each profile

### ISSUE THREAD

**Issue by AlyaGomaa** [stratosphereips/StratosphereLinuxIPS#255]
# Goal

keep a history of the user agents seen by zeek's http.log used by each profile

# How to implement it
1. Check slips documentation to find the module that deals with HTTP traffic
2. see how to extract the user agent from the HTTP flow sent there (this will be implemented in the module from step 1)
3. every time you see a new UA for a certain profile store it to the profileid's key in the database. this function will be implemented in the database file)
4. Find the directory inside dataset/ that has some HTTP traffic (HINT: it's a zeek dir, not a pcap)
5. now after adding the functions. test your code by running ./slips.py -f <zeek_dir_from_step_4> -o output_dir and making sure there's no errors

# Expected output

![image](https://user-images.githubusercontent.com/41242896/226309256-97c6e717-9285-4ae0-bb74-ae96e9dfaf30.png)

The user agents and profileid may be different in your case. Note that the goal is to "keep a  history of the past user agents" and not just store the last user agent in the db.

If your code is working and you can see something similar to the screenshot in your redis database, congrats! you can open a PR and we will merge it.

**Comment by pwnb0y** [comment]
working on it.
