### ISSUE TITLE
when publishing a new version, all slips files should be readin g the version from 1 place

### ISSUE THREAD

**Issue by AlyaGomaa** [stratosphereips/StratosphereLinuxIPS#268]
Created by Sebastian Garcia via monday.com integration. 🎉

**Comment by ashavijit** [comment]
@AlyaGomaa can you elaborate the issue

**Comment by AlyaGomaa** [comment]
right now slips version is hardcoded in config/slips.conf
and All CI files in the .github/workflow dir
and slips.py etc.
they should all be reading the version from 1 file, so that when publishing a new version of slips we change the version number in just 1 file
