### ISSUE TITLE
Auto publish macos images using CI

### ISSUE THREAD

**Issue by AlyaGomaa** [stratosphereips/StratosphereLinuxIPS#274]
Created by Alya Gomaa via monday.com integration. 🎉

**Comment by A-atmos** [comment]
Working on this one. Do we need to test for macos images seperately while publishing, or just create a publish of macos?

**Comment by AlyaGomaa** [comment]
yes testing and publishing. i'll check your PR thanks!

**Comment by A-atmos** [comment]
Hey, I just noticed in my PR that the tags weren't updated for the relevant image. Do we need to update the tags in the relevant images like `stratosphereips/slips:ubuntu` for ubuntu release?

**Comment by AlyaGomaa** [comment]
we publish 2 versions in dockerhub for each OS 

for ubuntu we publish:
`stratosphereips/slips:latest ` and `stratosphereips/slips:vx.x.x`

so for macos we should publish 2 images:
`stratosphereips/slips_macos_m1:latest` and `stratosphereips/slips_macos_m1:vx.x.x`

so i agree you should change the repo name not the tags, the tags will always be latest and the current version @A-atmos

**Comment by A-atmos** [comment]
Updated the workflow in PR. Thanks!
