### ISSUE TITLE
[FEATURE]: Pull Request Template

### ISSUE THREAD

**Issue by money8203** [stratosphereips/StratosphereLinuxIPS#278]
**Please Describe The Feature You Want**
Create a pull request template for the repository so that people can clarify the changes they have made 

If there are multiple solutions, please present each one separately. Save comparisons for the very end.)
No

**Comment by money8203** [comment]
#277

**Comment by Onyx2406** [comment]
Follow this: https://stratospherelinuxips.readthedocs.io/en/develop/contributing.html#beginner-tips-on-how-to-create-a-pr-in-slips

**Comment by AlyaGomaa** [comment]
Merged PR https://github.com/stratosphereips/StratosphereLinuxIPS/pull/277
