### ISSUE TITLE
Finish implementing these features

### ISSUE THREAD

**Issue by eldraco** [stratosphereips/StratosphereLinuxIPS#32]
This list of features should be implemented:

clientDestinationPortTotalBytesUDPEstablished
clientDestinationPortNumberOfFlowsTCPEstablished
clientDestinationPortNumberOfFlowsUDPNotEstablished
clientDestinationPortTotalPacketsTCPEstablished
clientDestinationPortNumberOfFlowsUDPEstablished
clientDestinationPortTotalPacketsTCPNotEstablished
clientDestinationPortTotalBytesUDPNotEstablished
clientDestinationPortTotalBytesTCPEstablished
clientDestinationPortTotalPacketsUDPNotEstablished
clientDestinationPortNumberOfFlowsTCPNotEstablished
clientDestinationPortTotalBytesTCPNotEstablished
clientDestinationPortTotalPacketsUDPEstablished

Not sure which ones we are already reading from the flow file or are in the DB. Check

**Comment by frenky-strasak** [comment]
I work on this.

**Comment by frenky-strasak** [comment]
All of them are already implemented.
