### ISSUE TITLE
KeyError: 'proto' in slips_files/core/profilerProcess.py

### ISSUE THREAD

**Issue by naturalnetworks** [stratosphereips/StratosphereLinuxIPS#327]
**Describe the bug**
During capture from an interface, the following error pops up quite often.

```
[ProfilerProcess-15] Traceback (most recent call last):e last 1 hr: 2. (2023/04/30 18:19:04)
  File "/home/user/StratosphereLinuxIPS/slips_files/core/profilerProcess.py", line 1784, in run
    self.process_zeek_input(line)
  File "/home/user/StratosphereLinuxIPS/slips_files/core/profilerProcess.py", line 565, in process_zeek_input
    line['proto'],
    ~~~~^^^^^^^^^
KeyError: 'proto'
```

Note that I am receiving a TZSP stream from a router and replaying it to a dummy interface.

**To Reproduce**
1. Set network interface to promisc (or use a dummy interface with tcpreplay)
2. ./slips.py -c config/slips.conf -i <network interface>
3. Confirm data eg tcpdump -i <network interface> -c 10
4. Wait for error to appear

**Expected behavior**
No key errors should appear during normal operation/during an interface capture.

**Branch**
Have tested both Master and Develop, issue seen on both.

**Environment (please complete the following information):**
 - OS: Ubuntu (Raspberry Pi)
 - Version: 23.04 (Linux 6.2.0-1004-raspi aarch64)
 - Python version: Python 3.11.2
 - Are you running slips in docker or locally? Locally

**Additional context**

Changing the following in profilerProcess.py makes the issue go away, but I'm not sure if it's the correct fix.

```
# 'proto': line['proto'],
'proto' : line.get('proto', ''),
```

**Comment by AlyaGomaa** [comment]
hey @naturalnetworks thanks for reporting!
fixed in PR #272
