### ISSUE TITLE
Threat Intelligence Feed

### ISSUE THREAD

**Issue by eldraco** [stratosphereips/StratosphereLinuxIPS#33]
For each Dst ip , have some info on the threat level of the ip.

Two ways to implement:

1- Download files of Feed information from some sources. And check the ip on them. For example https://threatfeeds.io/ 
2- Ask directly to Threat intel sources like VirusTotal, etc.

**Comment by frenky-strasak** [comment]
I would prefer to use virustotal, but you need to be signed up for using their API. If we use some file with IPs (for example from https://threatfeeds.io/) we would need to update time to time, but it is not so big deal maybe.

**Comment by frenky-strasak** [comment]
I would suggest to download "Bad IPs" file from https://threatfeeds.io/. There are 428858 IPs and we can update it in our github time to time.

**Comment by frenky-strasak** [comment]
I work on this.

**Comment by eldraco** [comment]
Perfect! testing!

**Comment by eldraco** [comment]
Now the module is working Frenky. But the file is being downloaded from the git repo. We need to download them from the internet or from a server we can control. Lets solve the issue of where we download the file please. @frenky-strasak

**Comment by frenky-strasak** [comment]
Of course! I will do it :+1:
