### ISSUE TITLE
AttributeError: 'ProfilerProcess' object has no attribute 'flow' in profilerProcess.py

### ISSUE THREAD

**Issue by naturalnetworks** [stratosphereips/StratosphereLinuxIPS#331]
**Describe the bug**
During capture from an interface, the following error pops up quite often.

```
Traceback (most recent call last):
  File "/home/user/StratosphereLinuxIPS/slips_files/core/profilerProcess.py", line 1198, in add_flow_to_profile
    if not self.is_supported_flow():
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/StratosphereLinuxIPS/slips_files/core/profilerProcess.py", line 1101, in is_supported_flow
    self.flow.starttime is not None
    ^^^^^^^^^
AttributeError: 'ProfilerProcess' object has no attribute 'flow'
```

Note that I am receiving a TZSP stream from a router and replaying it to a dummy interface.

**To Reproduce**
1. Set network interface to promisc (or use a dummy interface with tcpreplay)
2. ./slips.py -c config/slips.conf -i <network interface>
3. Confirm data eg tcpdump -i <network interface> -c 10
4. Wait for error to appear

**Expected behavior**
No key errors should appear during normal operation/during an interface capture.

**Branch**
Develop, issue **not** seen on Master

**Environment (please complete the following information):**
 - OS: Ubuntu (Raspberri Pi/ARM64)
 - Version: 23.04 (Linux 6.2.0-1004-raspi)
 - Python version: Python 3.11.2
 - Are you running slips in docker or locally? Locally

**Additional context**

Added more checks to see if 'self.flow' exists in profilerProcess.py (around line 1100). Probably broke something else but it runs.

```
         if not hasattr(self, 'flow'):
             return False
         return bool(
             self.flow is not None
             and hasattr(self.flow, 'starttime') and self.flow.starttime is not None
             and self.flow.type_ in supported_types
         )
```

**Comment by AlyaGomaa** [comment]
hey @naturalnetworks is it possible to send me the zeek flows that resulted in this error? you can delete all the sensitive info from them first?

**Comment by naturalnetworks** [comment]
Hi @AlyaGomaa emailed them to you, hope that's okay.

**Comment by AlyaGomaa** [comment]
hello @naturalnetworks yes got them, i'm currently investigating. will update you once it's fixed.
thank you!

**Comment by AlyaGomaa** [comment]
fixed in the latest develop. thanks for reporting!
