### ISSUE TITLE
'arp' vs 'ip neigh'

### ISSUE THREAD

**Issue by naturalnetworks** [stratosphereips/StratosphereLinuxIPS#332]
slips/modules/ip_info/ip_info.py line 440 runs the system command 'arp -a' to populate gw_MAC:

```
        # get it using arp table
        cmd = "arp -a"      
        output = subprocess.check_output(cmd.split()).decode()
        for line in output: 
            if gw_ip in line:
                gw_MAC = line.split()[-4]
                __database__.set_default_gateway('MAC', gw_MAC)
                return gw_MAC
```

If the arp command isn't found, the following error is raised:

```
2023/05/01 11:13:25.464006 [IP Info] Traceback (most recent call last):
  File "/home/user/StratosphereLinuxIPS/modules/ip_info/ip_info.py", line 504, in run
    self.get_gateway_MAC(ip)
  File "/home/user/StratosphereLinuxIPS/modules/ip_info/ip_info.py", line 441, in get_gateway_MAC
    output = subprocess.check_output(cmd.split()).decode()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'arp'
```

The arp command is part of the legacy net-tools package and is replaced by 'ip neigh' from the iproute2 package. 

I suggest:

Handle potential errors from the subprocess.

Update documentation, listing net-tools as a dependency
Check for the arp command

Or

Update documentation, listing net-tools or iproute2 as a dependency
Check for the arp or 'ip neigh' commands, use what is available

This ensures backwards compatibility. The differing outputs will need to be accommodated.

Or

Update documentation, listing iproute2 as a dependency
Check for the 'ip neigh' command

Update to accommodate different output.

Example 'arp -a' output:

```
router.home.arpa (192.0.2.1) at ab:cd:ab:cd:ab:cd [ether] on wlan0
```

Example 'ip neigh' output:

```
192.0.2.1 dev wlan0 lladdr ab:cd:ab:cd:ab:cd STALE
2001:0DB8:BEEF:CAFE::1 dev wlan0 lladdr ab:cd:ab:cd:ab:cd router REACHABLE
```

Added benefit in that ip neigh supports IPv6.

Thank you

**Comment by naturalnetworks** [comment]
I toyed around with the above options for a while and came to the conclusion that continuing with 'arp -a' is not really worth it. 'ip neigh show <gateway ip>' is easier.

```
        # get the gateway MAC address using 'ip neigh' 
        try:
            cmd = f"ip neigh show {gw_ip}"
            output = subprocess.check_output(cmd.split()).decode()
            gw_MAC = output.split()[4]
            __database__.set_default_gateway('MAC', gw_MAC)
            return gw_MAC
        except (FileNotFoundError, IndexError):
            return
```

**Comment by eldraco** [comment]
Hi @naturalnetworks , thanks for all the nice work.
I can see your point, since ip is a much modern and versatile command. However, our concern is that the ip command is actually not installed by default in many Linux distributions (like raspbian). 
So, even though  we can replace it with 'ip neigh show', we will need to have other dependency and installation problems in many systems. That is why decided for 'arp'.

If you can see a stronger reason why to use ip and not arp, or if ip is in as many systems as arp, then tell us and we will gladly change.

**Comment by naturalnetworks** [comment]
I'd say wherever you find net-tools installed, you'll also find iproute2. Net-tools has largely been untouched since 2009. In this particular case it wasn't installed at all (Ubuntu 23.04) which led me to suggest to avoid assuming the arp command will be available.

**Comment by eldraco** [comment]
Well, it is a good idea since the other tools are so old. And we can put it in the requirements and install scripts. You convinced us. We will move this to be merged. Thanks @naturalnetworks !

**Comment by eldraco** [comment]
Do you want to make a PR for this @naturalnetworks? So you can test and you appear as contributor? Or you prefer us doing it?

**Comment by naturalnetworks** [comment]
Thanks @eldraco . A PR will be a learning experience for me so I'll give it a go.

**Comment by eldraco** [comment]
Thanks! Yes it is a good place to start. Tell us if you need help in discord
