### ISSUE TITLE
TypeError: ProfilingFlowsDatabase.add_port() missing 1 required positional argument: 'port_type'

### ISSUE THREAD

**Issue by naturalnetworks** [stratosphereips/StratosphereLinuxIPS#333]
**Describe the bug**

Setting 'analysis_direction = all' in config/slips.conf  results in the following error during a capture:

```
Traceback (most recent call last):
  File "/home/user/StratosphereLinuxIPS/slips_files/core/profilerProcess.py", line 1259, in add_flow_to_profile
    self.handle_in_flows()
  File "/home/user/StratosphereLinuxIPS/slips_files/core/profilerProcess.py", line 1371, in handle_in_flows
    self.store_features_going_in(rev_profileid, rev_twid)
  File "/home/user/StratosphereLinuxIPS/slips_files/core/profilerProcess.py", line 1516, in store_features_going_in
    __database__.add_port(profileid, twid, self.flow, role, port_type)
TypeError: ProfilingFlowsDatabase.add_port() missing 1 required positional argument: 'port_type'
```

**To Reproduce**
1. Set analysis_direction to 'all' in slips.conf
2. Set network interface to promisc (or use a dummy interface with tcpreplay)
3. ./slips.py -c config/slips.conf -i <network interface>
4. Confirm data eg tcpdump -i <network interface> -c 10
5. Wait for error to appear

**Expected behavior**
No type error should show during normal operation.

**Branch**
Develop. Issue not seen in Master.

**Environment (please complete the following information):**
 - OS: Ubuntu (Raspberri Pi/ARM64)
 - Version: 23.04 (Linux 6.2.0-1004-raspi)
 - Python version: Python 3.11.2
 - Are you running slips in docker or locally? Locally

**Additional context**

Dug around in slips_files/core/profilerProcess.py and /slips_files/core/database/_profile_flow.py.

Confirmed that 'ProfilingFlowsDatabase.add_port()' requires the following:

```
    def add_port(
        self,
        profileid: str,
        twid: str,
        ip_address: str,
        columns: dict,
        role: str,
        port_type: str,
    ):
```

'def store_features_going_in(self, profileid, twid)' in profilerProcess.py is only setting 5 arguments, not 6.

```
__database__.add_port(profileid, twid, self.flow, role, port_type)
````

Changed profilerProcess.py to:

```
        # Add the srcip and srcport
        __database__.add_ips(profileid, twid, self.flow, role)
        port_type = 'Src'
        # __database__.add_port(profileid, twid, self.flow, role, port_type)
        __database__.add_port(
            profileid,
            twid,
            self.daddr_as_obj,
            self.column_values,
            role,
            port_type,
        )

        # Add the dstport
        port_type = 'Dst'
        # __database__.add_port(profileid, twid,self.flow, role, port_type)
        __database__.add_port(
            profileid,
            twid, 
            self.daddr_as_obj,
            self.column_values,
            role,
            port_type,
        )
```
Error no longer seen and code matches with the current Master.

**Comment by naturalnetworks** [comment]
My changes actually didn't work, causes the following error:

```
Traceback (most recent call last):sending traffic in the last 1 hr: 1. (2023/05/02 20:45:52)
  File "/home/user/StratosphereLinuxIPS/slips_files/core/profilerProcess.py", line 1260, in add_flow_to_profile
    self.handle_in_flows()
  File "/home/user/StratosphereLinuxIPS/slips_files/core/profilerProcess.py", line 1372, in handle_in_flows
    self.store_features_going_in(rev_profileid, rev_twid)
  File "/home/user/StratosphereLinuxIPS/slips_files/core/profilerProcess.py", line 1522, in store_features_going_in
    self.column_values,
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'ProfilerProcess' object has no attribute 'column_values'
```

A lot has changed with profilerProcess.py, not sure if I will be able to figure it out.

**Comment by AlyaGomaa** [comment]
this is fixed yesterday in the latest develop 
you can pull now and let us know if this problem persists.
Thank you so much for reporting!

**Comment by naturalnetworks** [comment]
Looking good so far. Thanks!
