### ISSUE TITLE
Apple M1 support?

### ISSUE THREAD

**Issue by Ondjultomte** [stratosphereips/StratosphereLinuxIPS#410]
**Describe the bug**
Can the docker images be run on apple silicon?

slips docker run -it -d --name slips stratosphereips/slips:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
5bfb9922f1a96b7c59b786f8f22739b397157d320c22b683e45cae18fee91396

**To Reproduce**
run docker run -it -d --name slips stratosphereips/slips:latest. on apple silicon

**Expected behavior**
docker images starts.

**Screenshots**

**Branch**
latest docker build

**Environment (please complete the following information):**
 - OS: MacOS Ventura
 

**Additional context**

**Comment by Ondjultomte** [comment]
I managed to run it now,

**Comment by eldraco** [comment]
Hi @Ondjultomte . Please see that there is a docker version called slips_macos_m1 here https://hub.docker.com/r/stratosphereips/slips_macos_m1 
However it is outdated, and we are working on it.
confirm it is working please

**Comment by Ondjultomte** [comment]
> Hi @Ondjultomte . Please see that there is a docker version called slips_macos_m1 here https://hub.docker.com/r/stratosphereips/slips_macos_m1 However it is outdated, and we are working on it. confirm it is working please

Doesnt work unfortunately

![image](https://github.com/stratosphereips/StratosphereLinuxIPS/assets/16661547/e6641cf9-9204-4fb0-8453-d701f68db5dc)
