### ISSUE TITLE
The image in documentation for installation page is missing

### ISSUE THREAD

**Issue by roshnaeem** [stratosphereips/StratosphereLinuxIPS#463]
**Describe the bug**
The documentation page for installation does not show the picture for the "[Building Slips from the Dockerfile](https://stratospherelinuxips.readthedocs.io/en/develop/installation.html#building-slips-from-the-dockerfile)" section.

**To Reproduce**
Go to [Building Slips from the Dockerfile](https://stratospherelinuxips.readthedocs.io/en/develop/installation.html#building-slips-from-the-dockerfile)

**Expected Behavior**
It should show the image, rather than the code for it. 

**Screenshot**

<img width="898" alt="Screenshot 2024-02-25 at 1 46 25 AM" src="https://github.com/stratosphereips/StratosphereLinuxIPS/assets/47316899/3e0f7f68-8d07-4cd4-8fe1-87bc9c254119">

**Comment by eldraco** [comment]
Do you want in the meantime to do a PR solving it @roshnaeem? If not we will fix, thanks
