### ISSUE TITLE
Unable to launch GUI

### ISSUE THREAD

**Issue by ooi18** [stratosphereips/StratosphereLinuxIPS#465]
**Describe the bug**
I am trying out this project following the instructions in the readme file. However, when I want to launch the web interface, I got the `ModuleNotFoundError: No module named 'slips_files'`. How can I resolve this error?

**To Reproduce**
1. Followed the steps in Usage -> Linux section in readme to run Slips in docker.
2. Followed the step to run `./webinterface.sh` mentioned in Graphical User Interface -> Web interface section in readme.
3. See error

**Expected behavior**
The webinterface.sh file will be run successfully and I can navigate to http://localhost:55000/ as mentioned in the readme file.

**Screenshots**
![slips-error1](https://github.com/stratosphereips/StratosphereLinuxIPS/assets/48976740/409f7f34-4439-4c5b-89bb-3a1fbe4199b6)

**Branch**
Master

**Environment (please complete the following information):**
 - OS: Debian
 - Version 11
 - Python version 3.8
 - Are you running slips in docker or locally? yes
 - Docker version (if running slips in docker) 24.0.7
 - Slips docker image used (if running slips in docker) stratosphereips/slips

**Comment by asimiqbl3** [comment]
I'm having same issue. I'd really appreciate if you can help resolve this error. Love the product you made!

**Comment by AlyaGomaa** [comment]
hello @asimiqbl3 and @ooi18, thanks for reporting!
Fixed here #478
