### ISSUE TITLE
Docker image "macosm1-p2p-image" throwing 'sklearn' error

### ISSUE THREAD

**Issue by roshnaeem** [stratosphereips/StratosphereLinuxIPS#467]
**Describe the bug**
The package `sklearn` is deprecated and needs to be removed or replaced by `scikit_learn` from requirements.txt.

**To Reproduce**
1. Follow the instructions to [Building Slips from the Dockerfile](https://stratospherelinuxips.readthedocs.io/en/develop/installation.html#building-slips-from-the-dockerfile)
2. Go to `macosm1-P2P-image` directory
3. Run 
```
docker build --no-cache -t slips -f Dockerfile .
```

**Expected behavior**
The image should be built

**Screenshots**
<img width="1081" alt="Screenshot 2024-02-27 at 4 11 02 PM" src="https://github.com/stratosphereips/StratosphereLinuxIPS/assets/47316899/90ec0802-02a8-4e07-852c-ee0382d41bd7">

The error: 
<img width="988" alt="Screenshot 2024-02-27 at 4 11 25 PM" src="https://github.com/stratosphereips/StratosphereLinuxIPS/assets/47316899/8ffed1c6-fcee-4f4c-8355-86c7a615067b">

**Comment by eldraco** [comment]
It is valid. Just check that maybe the p2p docker was not updated. check the requirements of the latest m1 without p2p.

**Comment by roshnaeem** [comment]
@eldraco, i am replacing `sklearn` with `scikit-learn` on [this line](https://github.com/stratosphereips/StratosphereLinuxIPS/blob/a6b9f7113c84e017eaebacb0d567b5af414fbc1e/docker/macosm1-P2P-image/requirements-macos-m1-docker.txt#L26). I tried removing the line too.  I tried removing `sklearn` in [requirements.txt](https://github.com/stratosphereips/StratosphereLinuxIPS/blob/a6b9f7113c84e017eaebacb0d567b5af414fbc1e/install/requirements.txt#L27) as well. 
However, it keeps giving me the same error, do i need to update something else too or change it somewhere else too?  It is not somehow reading my changes in the file and still trying to install sklearn. 

<img width="996" alt="Screenshot 2024-02-27 at 5 11 10 PM" src="https://github.com/stratosphereips/StratosphereLinuxIPS/assets/47316899/4ec39fd3-f246-480f-8f0f-d464de62e614">

**Comment by eldraco** [comment]
Ah yes, this is because in our deployment strategy, the Docker image is always built from master branch, and therefore if you only change the develop branch, it will still pull from master, and your changes are not there yet. 
So to do this:
I need to update the master branch first
then I can pull and build the docker

So from your PR is good if you only modify the file as you did

**Comment by roshnaeem** [comment]
Done @eldraco :)))Please check

**Comment by AlyaGomaa** [comment]
fixed here https://github.com/stratosphereips/StratosphereLinuxIPS/pull/470
