### ISSUE TITLE
Cannot start webinterface "No module named 'slips_files'"

### ISSUE THREAD

**Issue by maldwg** [stratosphereips/StratosphereLinuxIPS#479]
**Describe the bug**
I cannot open the GUI by using the provided shell script. When I try to do so, I receive the error 

root@LAPTOP:/StratosphereLinuxIPS# ./webinterface.sh
Traceback (most recent call last):
  File "webinterface/app.py", line 5, in <module>
    from analysis.analysis import analysis
  File "/StratosphereLinuxIPS/webinterface/analysis/analysis.py", line 8, in <module>
    from slips_files.common.slips_utils import utils
ModuleNotFoundError: No module named 'slips_files'

**To Reproduce**
1. run a docker container on Linux as described in the README
2. Run slips to analyze something (e.g. ./slips.py -f dataset/test7-malicious.pcap -o output_dir)
3. Try to run the web interface with ./webinterface.sh

**Expected behavior**
I would expect the import to be correct and the web GUI to open up/be accesible

**Branch**
Latest docker container version for Linux

**Environment (please complete the following information):**
 - OS: [Ubuntu]
 - Version [22.04]
 - Python version [3.8]
 - I am running slips in docker
 - Docker version (if running slips in docker) [24.0.7]
 - Slips docker image used: The default docker image mentioned in the documentation https://hub.docker.com/r/stratosphereips/slips

**Comment by eldraco** [comment]
Hi @maldwg yes I can confirm that now I can reproduce this error. We are in the process of solving it. Thanks!
The issue was with a new dependency import

**Comment by AlyaGomaa** [comment]
hello @maldwg 
this is the same issue as #465 , it was fixed in the develop branch yesterday, you can use it from develop until the changes are merged to master next Friday.

thanks for reporting! we appreciate it.

let us know how it goes :)
