### ISSUE TITLE
Small typo, a white space is needed in description of alert

### ISSUE THREAD

**Issue by AlyaGomaa** [stratosphereips/StratosphereLinuxIPS#485]
Created by Sebastian Garcia via monday.com integration. 🎉

**Comment by drstone-genius04** [comment]
hey @AlyaGomaa could you tell me more about the issue

**Comment by AlyaGomaa** [comment]
Slips. Version 1.0.12 (d697955f)
in the macos m1 image for p2p

We have this evidence
- Detected DNS answer with a blacklisted IP: 46.101.206.53 for query: urlhaus-api.abuse.chAS: DIGITALOCEAN-ASN, US AS14061SNI: urlhaus-api.abuse.ch Descripti
          on: IP is not expected be delivering unauthenticated SMTP email to any Internet mail server, such as dynamic and residential IP space. Source: PBL Spamhaus
           Maintained, spamhaus. threat level: medium.

This needs an extra space

'chAS'
ch is the country code, and AS is the beginning of the description
