### ISSUE TITLE
The detection of reused MAC is not working correctly

### ISSUE THREAD

**Issue by AlyaGomaa** [stratosphereips/StratosphereLinuxIPS#525]
Created by Alya Gomaa via monday.com integration. 🎉

**Comment by eldraco** [comment]
In pcap https://drive.google.com/file/d/1qMMiKDOBGE071PE-pkChIoAKuvSZMcjq/view?usp=sharing

alert

1970-01-01T00:02:13.704329+00:00 (TW 1): Src IP 192.168.1.113 . Detected A device changing IPs. IP 192.168.1.113 was found with MAC address 08:00:27:11:4e:fa but the MAC belongs originally to IP: 192.168.1.130.

but the ip 192.168.1.113 never sent any packet with that MAC

**Comment by AlyaGomaa** [comment]
hi @eldraco i see both IPs using that mac when checking the zeek logs of this pcap, in arp.log and in conn.log
`grep -r 08:00:27:11:4e:fa | grep 192.168.1.113` 
`grep -r 08:00:27:11:4e:fa | grep 192.168.1.130`
why do you think the detection is wrong?

**Comment by AlyaGomaa** [comment]
hi no issue probably it was another capture?

**Comment by eldraco** [comment]
Probably my mistake.
