### ISSUE TITLE
Redis - get_message(timeout=None)

### ISSUE THREAD

**Issue by frenky-strasak** [stratosphereips/StratosphereLinuxIPS#55]
The redis python function "get_message()" does not work with argument "timeout=None". 
It throws following error:
"
Error in run() of unsupported operand type(s) for *: 'NoneType' and 'int' 
"
The "get_message(timeout=None)" will wait (proccess is freezed) until new message arrives.

**Comment by frenky-strasak** [comment]
I am working on that.

**Comment by frenky-strasak** [comment]
I have found 2 solutions:

1. "pubsub.get_message(timeout=-1)"  ->  not official way, but works nice.
2. "for message in pubsub.listen():" -> official way and work nice as well.

**Comment by eldraco** [comment]
Perfect!
