### ISSUE TITLE
problem detecting "arp outside localnet" in  dataset/test9 and test16

### ISSUE THREAD

**Issue by AlyaGomaa** [stratosphereips/StratosphereLinuxIPS#554]
Created by Alya Gomaa via monday.com integration. 🎉

**Comment by eldraco** [comment]
Lay Patel worked on this and checked that there may not be an issue anymore. Needs confirming.

**Comment by lpp5139** [comment]
Destination ip is part of whitelist organization(facebook), hence no alert generated.

**Comment by AlyaGomaa** [comment]
thanks for pointing it out @lpp5139 
can you find that flow in our dataset/ directory and change the IP to something that would trigger this evidence for the integration tests??
so the idea is, we fake some flows in our dataset/ directory to be able to test most slips detections, the more evidence triggered in the integration tests the better.
