### ISSUE TITLE
Various small issues in README.md

### ISSUE THREAD

**Issue by MariaRigaki** [stratosphereips/StratosphereLinuxIPS#6]
1. Platforms: slips has also been tested in Ubuntu 16.04 LTS. Also is it OSX 10.9.5 (not IOS)?
2. Usage:  In Debian and Ubuntu the command to install argus is `sudo apt-get install argus-server argus-clients`. Unfortunately this installs the previous version of argus (2.x). Maybe we should add the required version and put a note that it might be better to install from source.
3. Features: the '-m' switch is mentioned in two places but I think this is '-f'. 
4. TODO: if these issues have been solved, maybe we should remove them or replace them with the list of wanted features.

**Comment by eldraco** [comment]
I completely agree. I will update the README.
1. Yes, It also runs on MacOs 10.10.x to 10.12.x
2. True. However it depends on the version of Debian. Un unstable argus is above 3.0.x. However, a good guide on how to install argus from source code is maybe better. Or a pointer to the source.
3. Thanks, yes. I forgot that in the README.
4. Yes, good point. I will put in here the new TODO and the ROADMAP.
Thanks!

**Comment by eldraco** [comment]
Put this in the README also.
