### ISSUE TITLE
Stop Zeek if slips is stopped.

### ISSUE THREAD

**Issue by eldraco** [stratosphereips/StratosphereLinuxIPS#60]

**Comment by frenky-strasak** [comment]
When I run:
./slips.py -r some_pcap_file.pcap
and then I stop it, the Zeek is abort (terminated) as well.

When was happened? Or for which command?

tested on Ubuntu 16.04

**Comment by eldraco** [comment]
It usually happens when Zeek takes much more time to process the pcap. So you need to try with a very large pcap. Then you stop slips and zeek continues to run in the backgroud

**Comment by eldraco** [comment]
Solved
