### ISSUE TITLE
Fix the format of the documentation

### ISSUE THREAD

**Issue by eldraco** [stratosphereips/StratosphereLinuxIPS#612]
The documentation is wrongly formated here

https://stratospherelinuxips.readthedocs.io/en/develop/installation.html#id1

Many parts are like this

![image](https://github.com/stratosphereips/StratosphereLinuxIPS/assets/2458867/d3cedc33-41cc-4d24-a3d2-030c2397ab50)

**Comment by AlyaGomaa** [comment]
fixed here [1ad7362](https://github.com/stratosphereips/StratosphereLinuxIPS/commit/1ad73623ca05ccf796647e6d705069d508a74cfd)
