### ISSUE TITLE
In test_zeek_dataset.py, Sometimes slips triggers this evidence  "Multiple empty HTTP connections to google.com' and sometimes it doesnt

### ISSUE THREAD

**Issue by AlyaGomaa** [stratosphereips/StratosphereLinuxIPS#642]
Created by Alya Gomaa via monday.com integration. 🎉

**Comment by lpp5139** [comment]
Hey @AlyaGomaa, can you give me more details about this? Maybe a specific zeek file or test case?

**Comment by AlyaGomaa** [comment]
Hey @patel-lay yes it is.
heppened here https://github.com/stratosphereips/StratosphereLinuxIPS/actions/runs/9697823294/job/26762978860?pr=596#step:5:134

usually, when i re-run the tests, it passes, the problem is sometimes it fails, like the detection is not consistent.
