### ISSUE TITLE
Info about IPs in timewindow files is not deterministic. 

### ISSUE THREAD

**Issue by frenky-strasak** [stratosphereips/StratosphereLinuxIPS#65]
For two runs of slips with a same input I got:
1.
	147.32.87.1 (1 times). Info: geocountry Czechia, asn CESNET z.s.p.o.
2.
	147.32.87.1 (1 times). Info: asn CESNET z.s.p.o., geocountry Czechia

It is same information but the order is not same. It is not a big problem however if somebody would like compare some files it gives him differences.

**Comment by eldraco** [comment]
Nice catch. Probably its related with
- the geocountry and asn is in a list in the DB, and we store them in this file in the same order as they are in the list.
- however that list is filled when each module ends, which may depend on other factors as amount of ip.

Solution: To use a dictionary to store them, and be sure each position is correctly printed.
