### ISSUE TITLE
Timestamp is every time "number.0"  (no microseconds there).

### ISSUE THREAD

**Issue by frenky-strasak** [stratosphereips/StratosphereLinuxIPS#66]
It is weird. Check it.

**Comment by frenky-strasak** [comment]
A bug found. We process the timestamp by:
`time.mktime(self.column_values['starttime'].timetuple()`
however this method ignores milliseconds. So instead of this we use now 
`datetime.strptime` 
with default time format: '%Y-%m-%d %H:%M:%S.%f' which is the most extended time format (as for me :D ). However maybe we should detect time format ?

**Comment by eldraco** [comment]
Done
