### ISSUE TITLE
States of connections are different for argus, zeek, suricata.

### ISSUE THREAD

**Issue by frenky-strasak** [stratosphereips/StratosphereLinuxIPS#72]
We have to standardize the states of connections, because they are different for argus, zeek, suricata.

**Comment by frenky-strasak** [comment]
As we can reed in suricata website we have only 3  states for suricata captures.
"
The amount of time Suricata keeps a flow in memory is determined by the Flow time-out.

There are different states in which a flow can be. Suricata distinguishes three flow-states for TCP and two for UDP. For TCP, these are: New, Established and Closed,for UDP only new and established. For each of these states Suricata can employ different timeouts.

The state new in a TCP-flow, means the period during the three way handshake. The state established is the state when the three way handshake is completed. The state closed in the TCP-flow: there a several ways to end a flow. This is by means of Reset or the Four-way FIN handshake.

New in a UDP-flow: the state in which packets are send from only one direction.

Established in a UDP-flow: packets are send from both directions.
"

source: https://suricata.readthedocs.io/en/suricata-4.1.4/configuration/suricata-yaml.html

**Comment by eldraco** [comment]
Solved
