### ISSUE TITLE
update how we store the acc threat  level and timewindow in alerts.json

### ISSUE THREAD

**Issue by AlyaGomaa** [stratosphereips/StratosphereLinuxIPS#729]
Created by Alya Gomaa via monday.com integration. 🎉

**Comment by AlyaGomaa** [comment]
put it in a dict

"Note":{“Description”: alert, acc threat level:.. , timewindow: 3}

**Comment by eldraco** [comment]
Isnt this done already?

**Comment by AlyaGomaa** [comment]
ah yes i think it's done
