### ISSUE TITLE
Data processing starts while modules are still loading

### ISSUE THREAD

**Issue by draliii** [stratosphereips/StratosphereLinuxIPS#74]
Modules are loaded in alphabetical order, and data processing will start even if some modules are not loaded yet. This can be observed when reading data from pcap with small amount of IP addresses, when a new module is created from the template in the newslips branch. No new_ip messages arrive, but new_flow seem to be working, because flows start throughout the whole pcap. Temporarily, this can be "solved" by renaming the module in question.

**Comment by frenky-strasak** [comment]
It is ready in new version. We have to wait for merging.

**Comment by eldraco** [comment]
Solved
