### ISSUE TITLE
This CI has the same name as the publishing CI

### ISSUE THREAD

**Issue by verovaleros** [stratosphereips/StratosphereLinuxIPS#779]
Each CI should have a specific name that allows to differentiate them: 

https://github.com/stratosphereips/StratosphereLinuxIPS/blob/fb4246db7fe7a2c0a63ab3fa5a2c0f751b25fbb2/.github/workflows/CI-production-testing.yml#L1

So when you browse the actions is not confusing:
![image](https://github.com/stratosphereips/StratosphereLinuxIPS/assets/2458879/fb9981e7-555d-4a90-9445-ba0810d6c4c2)

**Comment by AlyaGomaa** [comment]
hi @verovaleros thanks for reporintg. fixed.
