### ISSUE TITLE
Check if we can use true and false in slips.yaml instead of 'yes' and 'no'

### ISSUE THREAD

**Issue by AlyaGomaa** [stratosphereips/StratosphereLinuxIPS#821]

**Comment by patel-lay** [comment]
Hey @AlyaGomaa, we can do that. We can also declare **"**disable: "[template , ensembling, Flow ML Detection, Update Manager]"**"** directly as list. This will require significant changes, but it is a better way.

**Comment by AlyaGomaa** [comment]
@patel-lay i agreewant me to assign you to this issue?

**Comment by patel-lay** [comment]
Just focusing on Booleans for now(yes/no and true/false). Currently everything is string, working on converting to Booleans. Will update lists later.

**Comment by AlyaGomaa** [comment]
ok awesome thankssss
let's always use true/false instead of yes/no
