### ISSUE TITLE
Check why Slips is not exporting the strato letters on ctrl+c. 

### ISSUE THREAD

**Issue by AlyaGomaa** [stratosphereips/StratosphereLinuxIPS#824]

**Comment by patel-lay** [comment]
Hey @AlyaGomaa, you mean just moving line 690 above 686 in process_manager.py file? There are multiple definition of function "shutdown_gracefully", but this seems to be most logical.

**Comment by AlyaGomaa** [comment]
yes you're right @patel-lay 
but after moving the line, we'll need to test that we're able to export the strato letters on ctrl+c

**Comment by patel-lay** [comment]
Hey @AlyaGomaa, I modified the code, do you know how to test it? I don't know how to look for strato letters?

**Comment by AlyaGomaa** [comment]
you can test it manually by 
1. setting export_strato_letters to yes in the config file
2. add in the code to print something to the cli when the module starts exporting. 
3. run slips on a relatively large pcap
4. then press ctrl+c after a minute or two, before slips is done analyzing
5. if slips did print something (the result of step 2) then the exporting is done
6. check the output directory for the exported file, make sure the letters are exported there and the file is not empty

**Comment by AlyaGomaa** [comment]
fixed by  https://github.com/stratosphereips/StratosphereLinuxIPS/pull/909
