### ISSUE TITLE
Check if the clouds of Microsoft (onedrive) and Google Drive are included in the whitelist of Microsoft and Google respectively. If they are, delete then.

### ISSUE THREAD

**Issue by eldraco** [stratosphereips/StratosphereLinuxIPS#829]
The problem is that many APT groups use OneDrive to exfiltrate data, similar to using Dropbox. So it is not good if it is whitelisted.

check here for ips https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide

Check here for more info https://www.rapid7.com/globalassets/_pdfs/whitepaperguide/rapid7-Kimsukys-Phishing-and-Payload-Tactics_wp.pdf

**Comment by eldraco** [comment]
Similar with Google Drive. It should not be whitelisted.

**Comment by AlyaGomaa** [comment]
raw.githubusercontent.com too

**Comment by AlyaGomaa** [comment]
drive.google.com will always be whitelisted if google.com is whitelisted.
