### ISSUE TITLE
Dockerize?

### ISSUE THREAD

**Issue by stuchl4n3k** [stratosphereips/StratosphereLinuxIPS#87]
Hi stratofolks,

so this all looks very interesting :ok_hand:, but I am having pretty hard time getting it to work - esp. `scikit` (the documentation on deps seem to be outdated a bit) and I figured out that I might as well share my Dockerfile once I'm finished. 

WDYT?

Currently my WIP looks like this:

```Dockerfile
FROM debian:buster

# Install wget and add Zeek repository to our sources.
RUN apt update && apt install -y --no-install-recommends \
    wget \
    ca-certificates \
    gnupg \
 && echo 'deb http://download.opensuse.org/repositories/security:/zeek/Debian_10/ /' > /etc/apt/sources.list.d/security:zeek.list \
 && wget -nv https://download.opensuse.org/repositories/security:zeek/Debian_10/Release.key -O Release.key \
 && apt-key add - < Release.key \
 && rm Release.key

# Install Slips dependencies.
RUN apt update && apt install -y --no-install-recommends \
    curl \
    python3 \
    python3-certifi \
    python3-maxminddb \
    python3-pandas \
    python3-redis \
    python3-scipy \
    python3-sklearn \
    python3-urllib3 \
    python3-watchdog \
    redis-server \
    zeek \
 && ln -s /opt/zeek/bin/zeek /usr/local/bin/bro

# Download and unpack Slips.
RUN wget -nv https://github.com/stratosphereips/StratosphereLinuxIPS/archive/master.tar.gz -O /slips.tar.gz \
 && mkdir /slips \
 && tar xf /slips.tar.gz -C /slips --strip-components=1 \
 && rm /slips.tar.gz

# For Kalipso:
RUN curl -sL https://deb.nodesource.com/setup_10.x  | bash -
RUN apt install -y --no-install-recommends nodejs
RUN cd /slips/modules/blessed && npm install \
    async \
    ansi-colors \
    blessed \
    blessed-contrib \
    clipboardy \
    redis

# Switch to Slips installation dir.
WORKDIR /slips
CMD redis-server --daemonize yes && /bin/bash
```

Then build: `docker build -t slips -f Dockerfile .`
Run container: `docker run -it --rm --net=host slips`
Run Slips in container: `./slips.py -c slips.conf -i wlan0`

**Comment by eldraco** [comment]
Nice idea! thanks for code. We will implement it soon.
Thanks for trying it

**Comment by stuchl4n3k** [comment]
You're welcome.

**Comment by YaKaiLi** [comment]
> Hi stratofolks,
> 
> so this all looks very interesting 👌, but I am having pretty hard time getting it to work - esp. `scikit` (the documentation on deps seem to be outdated a bit) and I figured out that I might as well share my Dockerfile once I'm finished.
> 
> WDYT?
> 
> Currently my WIP looks like this:
> 
> ```dockerfile
> FROM debian:buster
> 
> # Install wget and add Zeek repository to our sources.
> RUN apt update && apt install -y --no-install-recommends \
>     wget \
>     ca-certificates \
>     gnupg \
>  && echo 'deb http://download.opensuse.org/repositories/security:/zeek/Debian_10/ /' > /etc/apt/sources.list.d/security:zeek.list \
>  && wget -nv https://download.opensuse.org/repositories/security:zeek/Debian_10/Release.key -O Release.key \
>  && apt-key add - < Release.key \
>  && rm Release.key
> 
> # Install Slips dependencies.
> RUN apt update && apt install -y --no-install-recommends \
>     curl \
>     python3 \
>     python3-certifi \
>     python3-maxminddb \
>     python3-pandas \
>     python3-redis \
>     python3-scipy \
>     python3-sklearn \
>     python3-urllib3 \
>     python3-watchdog \
>     redis-server \
>     zeek \
>  && ln -s /opt/zeek/bin/zeek /usr/local/bin/bro
> 
> # Download and unpack Slips.
> RUN wget -nv https://github.com/stratosphereips/StratosphereLinuxIPS/archive/master.tar.gz -O /slips.tar.gz \
>  && mkdir /slips \
>  && tar xf /slips.tar.gz -C /slips --strip-components=1 \
>  && rm /slips.tar.gz
> 
> # For Kalipso:
> RUN curl -sL https://deb.nodesource.com/setup_10.x  | bash -
> RUN apt install -y --no-install-recommends nodejs
> RUN cd /slips/modules/blessed && npm install \
>     async \
>     ansi-colors \
>     blessed \
>     blessed-contrib \
>     clipboardy \
>     redis
> 
> # Switch to Slips installation dir.
> WORKDIR /slips
> CMD redis-server --daemonize yes && /bin/bash
> ```
> 
> Then build: `docker build -t slips -f Dockerfile .`
> Run container: `docker run -it --rm --net=host slips`
> Run Slips in container: `./slips.py -c slips.conf -i wlan0`

woooo! great job!

**Comment by eldraco** [comment]
This is working now!
