### ISSUE TITLE
'psutil' and other libraries are not installed in the install.sh

### ISSUE THREAD

**Issue by eldraco** [stratosphereips/StratosphereLinuxIPS#884]
**Describe the bug**
When installing the environment using `install/install.sh` is not installed.

`ModuleNotFoundError: No module named 'psutil'`

**To Reproduce**
1. Go to branch  develop
2. run `install/install.sh`
3. run slips `./slips.py -h`

**Branch**
develop

**Environment (please complete the following information):**
 - OS: Docker for macos m1
 - Version Docker version 27.1.1, build 6312585
 - Python version Python 3.9.2 (by hand)
 - Are you running slips in docker? yes
 - Slips docker image used (if running slips in docker) other

**Comment by eldraco** [comment]
Mmmm I see now that this library was not for Slips, but for some docker manager. I will explore. 
I was running  this as part of the new Docker Development, that you can develop using vscode inside your local dockers

**Comment by eldraco** [comment]
Same happens with redis

`ModuleNotFoundError: No module named 'redis'`

**Comment by eldraco** [comment]
Same with `ModuleNotFoundError: No module named 'tldextract'`

**Comment by AlyaGomaa** [comment]
also we should install zeek dependening on the platform in install.sh and not just assume it's 20.04

**Comment by AlyaGomaa** [comment]
also install.sh should be using install/requirements.txt

**Comment by AlyaGomaa** [comment]
fixed in #888
