### ISSUE TITLE
Evidence not generating for pcap in ubuntu-image docker

### ISSUE THREAD

**Issue by patel-lay** [stratosphereips/StratosphereLinuxIPS#903]
**Describe the bug**
Evidence is not generating for pcap files in ubuntu-image

**To Reproduce**
1. Go to branch develop
2. run:  docker run -it --rm --net=host -p 55000:55000 -v "/mnt/c/Users/Lay Patel/Desktop/Slips/StratosphereLinuxIPS":/StratosphereLinuxIPS slips
3. run: ./slips.py -e 1 -f dataset/test7-malicious.pcap

**Expected behavior**
Evidence should be generated. I can confirm that zeek_files are being generated.  

**Screenshots**
![image](https://github.com/user-attachments/assets/af75c183-d0de-404b-b5b1-984c466cc001)

Normal tests are working fine. 
![image](https://github.com/user-attachments/assets/d2caa0e1-d5b6-4218-a495-4fdd0d03b57c)

**Branch**
Develop

**Environment (please complete the following information):**
 - OS: windows WSL
 - Version: latest develop branch 
 - Python version: 3.10.12
 - Are you running slips in docker or locally? docker
 - Docker version (if running slips in docker): 4.29.0
 - Slips docker image used (if running slips in docker): ubuntu-image

**Comment by patel-lay** [comment]
@AlyaGomaa, there are no error logs. I build my own image and mapped to my repo. 

I found a way around. I was able to generate zeek files, so I had to re-run the zeek files generated. 
![image](https://github.com/user-attachments/assets/6d0a6a90-21ac-4d28-b59e-a274eead99ff)

**Comment by AlyaGomaa** [comment]
So we can close the issue now right? @patel-lay

**Comment by patel-lay** [comment]
@AlyaGomaa, yes you can close it
