### ISSUE TITLE
Conn.py of Flowalerts (and probably all modules?) are not reading all conn.log flows

### ISSUE THREAD

**Issue by AlyaGomaa** [stratosphereips/StratosphereLinuxIPS#910]
Here's what i tried:
* added a variable to track how many times check_non_http_port_80_conns() in conn.py of flowalerts was called. for reference this one should be called on every conn.log flow 
*  gave slips dataset/test9-mixed-zeek-dir/conn.log, which has 577 flows
* printed the variable when flowalerts stops

sometimes it printed 255, 271, etc.
So Slips never reached that function 577 times!

**Comment by patel-lay** [comment]
Hey @AlyaGomaa, is this similar to the http log errors we encountered before?

**Comment by AlyaGomaa** [comment]
hello @patel-lay yes you're right. this is related to why CI sometimes fails and sometimes passes, and why slips doesn't give the exact evidence on each run.
i'll be working on this one because it's a bit advnced

**Comment by AlyaGomaa** [comment]
fixed in #918
