### ISSUE TITLE
Kalipso Unable to display the data as a chart

### ISSUE THREAD

**Issue by denglq** [stratosphereips/StratosphereLinuxIPS#94]
Can you answer a question for me?（Sorry, my English is not very good） 
I have installed Kalipso tools like this：
![image](https://user-images.githubusercontent.com/16702031/80577339-4db99b80-8a39-11ea-913c-b60475896592.png)
After I start the program with this command ：
`./slips.py -c ./slips.conf -G -f zeek_files/`
, the GUI interface looks like this：
![image](https://user-images.githubusercontent.com/16702031/80577667-d801ff80-8a39-11ea-9f7c-0355e5f79bc4.png)
and  I start the program with this command:
`./slips.py -c ./slips.conf -G -r ./2019-10-05-traffic-analysis-exercise-part-1.pcap`
the GUI interface looks like this：
![image](https://user-images.githubusercontent.com/16702031/80577862-2d3e1100-8a3a-11ea-9f3c-122434c15ee9.png)
And keep doing this until the program stops。
Please tell me what to do to solve this problem. Thank you!

**Comment by denglq** [comment]
Using `-i` as a data source will also produce the same chart。

**Comment by eldraco** [comment]
Hi denglq
Did you try all the advices about strange characters in ncurses? 
We are using blessed, but the principle is the same.
See
https://askubuntu.com/questions/868881/problem-ubuntu-putting-out-characters-in-both-utf-8-and-iso-8859-1
https://github.com/scarygliders/X11RDP-o-Matic/issues/45
