### ISSUE TITLE
Bug in set_host_ip, develop branch, commit 8b015e7

### ISSUE THREAD

**Issue by eldraco** [stratosphereips/StratosphereLinuxIPS#97]
[Main] Total Number of Profiles in DB so far: 810. Modified Profiles in the last TW: 1. (2020-08-17--09:33:56)
Network is unreachable
Traceback (most recent call last):
  File "./slips.py", line 314, in <module>
    __database__.set_host_ip(hostIP)
  File "/xxx/StratosphereLinuxIPS/slips/core/database.py", line 1562, in set_host_ip
    self.r.sadd('hostIP', ip)
  File "xxx/python3.7/site-packages/redis/client.py", line 2208, in sadd
    return self.execute_command('SADD', name, *values)
  File "xxx/python3.7/site-packages/redis/client.py", line 877, in execute_command
    conn.send_command(*args)
  File "/xxx/python3.7/site-packages/redis/connection.py", line 720, in send_command
    self.send_packed_command(self.pack_command(*args),
  File "xxx/python3.7/site-packages/redis/connection.py", line 771, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "xxx/python3.7/site-packages/redis/connection.py", line 121, in encode
    "bytes, string, int or float first." % typename)
redis.exceptions.DataError: Invalid input of type: 'NoneType'. Convert to a bytes, string, int or float first.
[Evidence] 	DETECTED IP: 192.168.1.111 due to LSTM C&C channels detection, score: 0.71218735. Accumulated evidence: 50.0
[VirusTotal] Network is not available, waiting 10s
[VirusTotal] Network is not available, waiting 10s
[Evidence] 	DETECTED IP: 10.211.167.72 due to New horizontal port scan detected to port 443. Not Estab TCP from IP: 10.211.167.72. Tot pkts sent all IPs: 3. Accumulated evidence: 15.0
[Evidence] 	DETECTED IP: 147.32.185.28 due to New horizontal port scan detected to port 443. Not Estab TCP from IP: 147.32.185.28. Tot pkts sent all IPs: 12. Accumulated evidence: 50.0

**Comment by kamilababayeva** [comment]
Can you also tell when it is happenning?? when you run it on your interface? from the beginning or after some time?

**Comment by eldraco** [comment]
Yes, it is run from my interface. Run ok for some hours, then change networks and it worked ok, but suddenly had the error. I dont recall any special action.
Please remember that I changed the code in slips.py where this check is made. But i didnt changed how is made.
Also, remember that the check of the set_host_ip was done if there was no data in a TW from the host ip. However now we changed how we 'know' if a TW was not updated. I will give more details

**Comment by kamilababayeva** [comment]
Hello! Fixed. The computer was without network for a while, and when the host IP was checked again, None was returned. None value raised an error when putting into the database. Now I do check before putting host IP in database.
