### ISSUE TITLE
TypeError can't subtract offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by flaeckli** [stratosphereips/StratosphereLinuxIPS#987]
**Describe the bug**
SLIPS is running nativ on Ubuntu and monitoring one interface. (Currently in Train mode)
Slips is able to collect data but throws this error every 5-10 Seconds

**To Reproduce**
I used the master branch for this test

The error log is below 
[errors.log](https://github.com/user-attachments/files/16994360/errors.log)

```
```
![image](https://github.com/user-attachments/assets/40c4e03d-6563-4763-b971-9c56ec8bf968)

**Branch**
Master 

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Python version 3.10

 - Are you running slips in docker or locally? locally on Server
 

**Additional context**
I addet the error log below

**Comment by AlyaGomaa** [comment]
hi @flaeckli thank you for reporting this, we appreciate it!

It's fixed in the latest develop.
Let me know if you're still seeing this error.
